'use client'
import Head from "next/head";
import axios from "axios";
import Image from "next/image";
 
 
import { useState } from "react";


export default function Home() {
  const [city,setCity] = useState('')
  const [weather,setWeather] = useState({})
  const {loading,setLoading} = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}&units=metric`
   
 const fetchWeather = (e) => {
  axios.get(url).then((response)=>{
    e.preventDefault()
    setLoading(true)
    setWeather(response.data)
    console.log(response.data)
  })
  setCity('')
  setLoading(false)
 }
 

  return (
     <div>
      <Head>
        <title>Weather - NEXT APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
   <Image src='https://images.unsplash.com/photo-1601134467661-3d775b999c8b?q=80&w=1075&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
   layout='fill'
   />
    </div>
  )
}
 